// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissPaulingBot.Common;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MissPaulingBot.Migrations
{
    [DbContext(typeof(PaulingDbContext))]
    [Migration("20221008000310_NewProvider")]
    partial class NewProvider
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MissPaulingBot.Common.Models.ArtistApplication", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at");

                    b.Property<string>("UploadUrl")
                        .HasColumnType("text")
                        .HasColumnName("upload_url");

                    b.HasKey("UserId")
                        .HasName("pk_artist_applications");

                    b.ToTable("artist_applications", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.BlacklistedUser", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("moderator_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_blacklisted_users");

                    b.ToTable("blacklisted_users", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.ContestSetting", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool>("AllowSubmissions")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_submissions");

                    b.Property<decimal>("BannerChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("banner_channel_id");

                    b.Property<decimal>("IconChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("icon_channel_id");

                    b.HasKey("GuildId")
                        .HasName("pk_contest_settings");

                    b.ToTable("contest_settings", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.DmMessageTemplate", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("AuthorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Response")
                        .HasColumnType("text")
                        .HasColumnName("response");

                    b.HasKey("Name")
                        .HasName("pk_dm_message_templates");

                    b.ToTable("dm_message_templates", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.ModApplication", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<string>("AbuseResponse")
                        .HasColumnType("text")
                        .HasColumnName("abuse_response");

                    b.Property<string>("AgeResponse")
                        .HasColumnType("text")
                        .HasColumnName("age_response");

                    b.Property<string>("AvailabilitiesResponse")
                        .HasColumnType("text")
                        .HasColumnName("availabilities_response");

                    b.Property<string>("ButtingHeadsResponse")
                        .HasColumnType("text")
                        .HasColumnName("butting_heads_response");

                    b.Property<string>("ButtonsResponse")
                        .HasColumnType("text")
                        .HasColumnName("buttons_response");

                    b.Property<string>("ChangeResponse")
                        .HasColumnType("text")
                        .HasColumnName("change_response");

                    b.Property<string>("ChannelsResponse")
                        .HasColumnType("text")
                        .HasColumnName("channels_response");

                    b.Property<bool>("HasApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("has_applied");

                    b.Property<string>("PersonalResponse")
                        .HasColumnType("text")
                        .HasColumnName("personal_response");

                    b.Property<string>("QualificationResponse")
                        .HasColumnType("text")
                        .HasColumnName("qualification_response");

                    b.Property<string>("ReasonResponse")
                        .HasColumnType("text")
                        .HasColumnName("reason_response");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_mod_applications");

                    b.ToTable("mod_applications", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.ModmailVerification", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.HasKey("UserId")
                        .HasName("pk_modmail_verifications");

                    b.ToTable("modmail_verifications", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.ServerEmoji", b =>
                {
                    b.Property<decimal>("EmojiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("emoji_id");

                    b.Property<int>("Usage")
                        .HasColumnType("integer")
                        .HasColumnName("usage");

                    b.HasKey("EmojiId")
                        .HasName("pk_server_emojis");

                    b.ToTable("server_emojis", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.Spectator", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("GivenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("given_at");

                    b.HasKey("UserId")
                        .HasName("pk_spectators");

                    b.ToTable("spectators", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.StreamerApplication", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<string>("ContentAnswer")
                        .HasColumnType("text")
                        .HasColumnName("content_answer");

                    b.Property<string>("ReasonAnswer")
                        .HasColumnType("text")
                        .HasColumnName("reason_answer");

                    b.HasKey("UserId")
                        .HasName("pk_streamer_applications");

                    b.ToTable("streamer_applications", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreationUrl")
                        .HasColumnType("text")
                        .HasColumnName("creation_url");

                    b.Property<decimal>("CreatorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("creator_id");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("message_id");

                    b.Property<int>("SubmissionType")
                        .HasColumnType("integer")
                        .HasColumnName("submission_type");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.UserNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("GivenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("given_at");

                    b.Property<decimal>("ModeratorId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("moderator_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user_notes");

                    b.ToTable("user_notes", (string)null);
                });

            modelBuilder.Entity("MissPaulingBot.Common.Models.Vote", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<int>("BannerVote")
                        .HasColumnType("integer")
                        .HasColumnName("banner_vote");

                    b.Property<int>("IconVote")
                        .HasColumnType("integer")
                        .HasColumnName("icon_vote");

                    b.HasKey("UserId")
                        .HasName("pk_votes");

                    b.ToTable("votes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
